### ISSUE TITLE
project file (.vcxproj) missing

### ISSUE THREAD

**Issue by NPatch** [glls/gl3dv#1]
Hi,
Trying to build the repository but the project file is missing so not sure how it links to dependencies and what they are.

Thanks

**Comment by glls** [comment]
Hello NPatch, 
project file updated, 
now I need to find some time to compile the latest coin3d on windows and linux.

**Comment by NPatch** [comment]
I tried with Boost 1.45.0.
Also I had to download coin, sowin(GUI) and simage(texture loader) and use the same installation directory for all(so gl3dv can find them easily). Also built for both Debug, Release for VS2019 x64.

Had to reset all overridden paths(e.g. output, intermediary etc) in gl3dv solution due to issues(some of them didn't match).

This is minor, but changed COIN3DDIR to Coin_DIR as an environment var name as it seems to be recommended by coin( https://github.com/coin3d/coin/pull/241).

Lastly, while I think the solution was cmake generated, check out [property sheets in VS](https://twitter.com/npatsiouras/status/1245394415629283333) for reference.  Library dependencies in VS can be a bit easier to deal with. Added bonus, aggregating all include paths in one INCLUDE_DEPENDENCY_PATHS macro means you can later just use the User Macros sheet to add a new library without moving around. Single point of reference.
